### ISSUE TITLE
Openblas scipy error after installing gcc-5

### ISSUE THREAD

**Issue by tcfuji** [Homebrew/homebrew-python#226]
Using OS X 10.10.3 and even when reinstalling numpy and scipy with `--with-openblas`, I'm getting the following after brew installing gcc-5:

```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-e28645dca64e> in <module>()
      1 from pandas import read_csv
----> 2 from sklearn.linear_model import LogisticRegression
      3 from sklearn.metrics import accuracy_score
      4 import numpy as np
      5 from sklearn.cross_validation import cross_val_score

/usr/local/lib/python2.7/site-packages/sklearn/linear_model/__init__.py in <module>()
     10 # complete documentation.
     11 
---> 12 from .base import LinearRegression
     13 
     14 from .bayes import BayesianRidge, ARDRegression

/usr/local/lib/python2.7/site-packages/sklearn/linear_model/base.py in <module>()
     20 import numpy as np
     21 import scipy.sparse as sp
---> 22 from scipy import linalg
     23 from scipy import sparse
     24 

/usr/local/lib/python2.7/site-packages/scipy/linalg/__init__.py in <module>()
    159 from .linalg_version import linalg_version as __version__
    160 
--> 161 from .misc import *
    162 from .basic import *
    163 from .decomp import *

/usr/local/lib/python2.7/site-packages/scipy/linalg/misc.py in <module>()
      3 import numpy as np
      4 from numpy.linalg import LinAlgError
----> 5 from . import blas
      6 
      7 __all__ = ['LinAlgError', 'norm']

/usr/local/lib/python2.7/site-packages/scipy/linalg/blas.py in <module>()
    153 import numpy as _np
    154 
--> 155 from scipy.linalg import _fblas
    156 try:
    157     from scipy.linalg import _cblas

ImportError: dlopen(/usr/local/lib/python2.7/site-packages/scipy/linalg/_fblas.so, 2): Library not loaded: /usr/local/lib/gcc/4.9/libgfortran.3.dylib
  Referenced from: /usr/local/opt/openblas/lib/libopenblas_core2p-r0.2.14.dylib
  Reason: image not found
```

It looks like it's looking for my old gcc-4.9 but not using the new gcc-5 version.

**Comment by tdsmith** [comment]
You'll need to rebuild openblas as well, with --build-from-source, until homebrew-science updates the openblas bottle.

**Comment by iml** [comment]
OpenBLAS bottle has been updated, should trigger an upgrade also.

**Comment by tdsmith** [comment]
Should be resolved by #227. Thanks for reporting!

**Comment by puiseux** [comment]
so what ? I had the same problem, I uninstall/install bumpy, scipy, then i unlink/link all... Error remains.
I also uninstall/install gcc5. Same result.
How can I deal with this error ?

**Comment by tdsmith** [comment]
Please open a new issue and provide more detail about the problem you're experiencing.
